### ISSUE TITLE
Output pdf has wrong colour, incorrect translation of markup, and wrong scaling

### ISSUE THREAD

**Issue by zain910128** [py-pdf/pypdf#1615]
I am converting a PDF to A4 paper size and the output pdf has several bugs:

1. Wrong colour of markup. Gone from Red to black.
2. Incorrect translation of markup. It is slightly to the right whereas it should be exactly overlapping the background grid.
3. Wrong scaling (see comment in the attached screenshot)
4. Lack of central alignment as per transformation in code. Expectation is that there should be equal gap on top and bottom of the page, but the output has only empty space on top.
5. The thick and thin lines of the background grid have been interchanged (strangest bug).

The input file is:
[graph_letter.pdf](https://github.com/py-pdf/pypdf/files/10671366/graph_letter.pdf)

The output file is:
[graph_letter_output.pdf](https://github.com/py-pdf/pypdf/files/10671367/graph_letter_output.pdf)

A side by side comparison is:
<img width="1409" alt="comparison" src="https://user-images.githubusercontent.com/31308724/217144747-3901ad27-a842-4aa0-aee3-05dd852619b1.png">

I am using pypdf-3.4.0 in Google Colab.
The code used is:
```python
from pypdf import PdfReader, PdfWriter, Transformation, PageObject, PaperSize
from pypdf.generic import RectangleObject

reader = PdfReader("input.pdf")
page = reader.pages[0]
writer = PdfWriter()

A4_w = PaperSize.A4.width
A4_h = PaperSize.A4.height

# resize page to fit *inside* A4
h = float(page.mediabox.height)
w = float(page.mediabox.width)
scale_factor = min(A4_h / h, A4_w / w)
print(scale_factor)

transform = (
    Transformation()
    .scale(scale_factor, scale_factor)
    .translate(A4_w / 2 - w * scale_factor / 2, A4_h / 2 - h * scale_factor / 2)
)
page.add_transformation(transform)

page.cropbox = RectangleObject((0, 0, A4_w, A4_h))

# merge the pages to fit inside A4

# prepare A4 blank page
page_A4 = PageObject.create_blank_page(width=A4_w, height=A4_h)
page.mediabox = page_A4.mediabox
page_A4.merge_page(page)

writer.add_page(page_A4)
writer.write("output.pdf")
```

Please let me know if I am doing something wrong.

**Comment by pubpub-zz** [comment]
I've looked quickly and here are my conclusions:
a) you are using add_transformation which is only affecting the content and do not resize/repose the annotations (the red shapes/curves are actually annotations and not part of the original page) if you use add_transformation with pages part of a PdfWriter this should be fixed.
b) you have extended the cropping so more elements of the grid are shown:
c) about color change : I see no difference with acrobat reader. 🤔😑
d) (from my test) :
this is the code I propose
```
from pypdf import PdfReader, PdfWriter, Transformation, PageObject, PaperSize 
from pypdf.generic import RectangleObject 
 
reader = PdfReader("graph_letter.pdf") 
page = reader.pages[0] 
writer = PdfWriter() 
 
A4_w = PaperSize.A4.width 
A4_h = PaperSize.A4.height 
 
# resize page to fit *inside* A4 
h = float(page.mediabox.height) 
w = float(page.mediabox.width) 
scale_factor = min(A4_h/h, A4_w/w) 
print(scale_factor, A4_w/2 - w*scale_factor/2 , A4_h/2 - h*scale_factor/2) 

# prepare A4 blank page 
page_A4 = writer.add_blank_page(width = A4_w, height = A4_h) 
page_A4.merge_transformed_page( 
    page, 
    Transformation().scale(scale_factor,scale_factor).translate( 
        A4_w/2-w*scale_factor/2, 
        A4_h/2-h*scale_factor/2) 
    ) 
writer.write("graph_letter_output.pdf") 
```

**Comment by zain910128** [comment]
Your suggested code works better now. Thank you.

However, the colour issue is still present.

Like you said, the colour is the same in Adobe Acrobat, but it is different in mac's Preview and also when i open the pdf in Chrome browser (colour is white) and also when i view in Google drive.

The input file does not have this problem so the output file is also expected to be the same.

**Comment by pubpub-zz** [comment]
The color issue has been understand and fixed : During the copy, the field "/N" in the ICCBased attribute was not correctly copied (wrongly ignored)
This is fixed in #1635

**Comment by zain910128** [comment]
Is this fix available in the latest version if i do a pip install ?

**Comment by pubpub-zz** [comment]
No it has still to be merged and released

**Comment by MartinThoma** [comment]
pypdf==3.50 was just released :tada:

**Comment by pubpub-zz** [comment]
> pypdf==3.50 was just released 🎉

yes but the PR was not part of it... wait for next version 😉

**Comment by MartinThoma** [comment]
Oh, damn :sweat_smile: :see_no_evil:  I'm sorry :see_no_evil:
