### ISSUE TITLE
PyPDF2 should not overwrite warnings.formatwarning.

### ISSUE THREAD

**Issue by podloucky-init** [py-pdf/pypdf#67]
Hello,

PyPDF2 1.2.0 overwrites warnings.formatwarning with its own implementation (utils._formatwarning) in pdf.py line 74:

```
warnings.formatwarning = utils._formatwarning
```

Unfortunately this may cause severe side-effects if PyPDF2 is imported in a larger application. In our case the PyPDF2 implementation of formatwarning caused IndexErrors whenever a warning was raised somewhere else (and the filename argument was not to the formatter's liking).

Personally, I do not think that it is a good idea for a library to interfere with the global logging/warning infrastructure.

P.S.: Apart from this problem, we have been using PyPDF2 successfully for some time now. Nice piece of software!

**Comment by pavelbrych** [comment]
Hello,
we just run into the same problems as described here with overwritten showwarning method in larger project (interferes with SqlAlchemy). Constructor parameter for PdfFileReader() to turn custom implementation off does the trick, but unfortunately PdfFileReader() is instantiated also inside PdfFileMerger.merge() method and there is no option to turn custom showwarning method here. Would it be possible to add such option, if removing this code entirely is - for some reason - not preferred?

Thank you for great software, apart from this works nice for us.

**Comment by andrecp** [comment]
Hi @pavelbrych I've fixed it here (I hope): https://github.com/opendesk/PyPDF2/commit/47b3e6d1dea09f0d10af833ce56303fc7af9a4a6

I've done a PR to the library.

Cheers

**Comment by Kiza** [comment]
Fyi, it interferes with pandas as well.

**Comment by CartierPierre** [comment]
Please fix that ... 
```
file = filename.replace("/", "\\").rsplit("\\", 1)[1] # find the file name
IndexError: list index out of range
```

**Comment by gaspa93** [comment]
Same as @Kiza and @CartierPierre: it breaks with Pandas warnings

**Comment by Biganon** [comment]
Still not fixed, I was becoming crazy trying to understand how numpy could cause PyPDF2 errors...

**Comment by sjvdm** [comment]
Same issue here with version 1.26 - getting numpy related errors with PyPDF2

**Comment by MartinThoma** [comment]
I think this issue got solved with https://github.com/py-pdf/PyPDF2/commit/89a29ef05ed4684c62051e5831415217ba36f308 (February 2014, [v1.25.1](https://github.com/py-pdf/PyPDF2/releases/tag/v1.25.1)):

`warnings.formatwarning = utils._formatwarning` was formerly in `pdf.py` (e.g. [1311d787725f4601503876b0feb8c09f2f992536](https://github.com/py-pdf/PyPDF2/blob/1311d787725f4601503876b0feb8c09f2f992536/PyPDF2/pdf.py#L74)), but it's not longer there.

**Comment by MartinThoma** [comment]
Uh, I've just seen `warnings.showwarning = _showwarning`

**Comment by MartinThoma** [comment]
Let's connect the issues:

- #67 (this issue): Let's take this to bundle discussions
- #641 - was fixed by another PR
- #452 - was fixed via #612
- #243 : Merged and will be released in April 2022. This gives people the possibility to disable the overwriting of warnings. Be aware that I want to get rid of it completely (see [cleanup plan](https://github.com/py-pdf/PyPDF2/discussions/752) and #225 )

**Comment by MartinThoma** [comment]
This was fixed with PyPDF2 2.0.0. Thank you all for pointing out the issues!
